name: food_delivery
description: "FoodEx - Community-driven food marketplace. A modern Flutter app connecting customers with local home chefs, featuring a complete wallet system and Moroccan-inspired design."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# App version and build number
version: 1.0.0+1

# Flutter SDK constraints
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

# Production dependencies
dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8

  # Authentication & OTP
  otp_pin_field: ^1.2.0+2

  # User Interface
  flutter_rating_bar: ^4.0.1
  flutter_easyloading: ^3.0.5

  # Media & Files
  image_picker: ^1.1.2

  # Maps & Location (Mobile platforms)
  google_maps_flutter: ^2.9.0
  custom_map_markers: ^0.0.2+1

  # Networking
  http: ^1.2.2

  # Storage & Preferences
  shared_preferences: ^2.3.2

  # Internationalization & Time
  intl: ^0.19.0
  flutter_timezone: ^2.1.0

  # Dependency Injection
  get_it: ^8.0.2

  # Platform-specific dependencies
  # Web platform
  flutter_web_plugins:
    sdk: flutter

  # Desktop platforms (Windows, macOS, Linux)
  window_manager: ^0.4.2
  screen_retriever: ^0.1.9

  # File system access (Desktop & Mobile)
  path_provider: ^2.1.4
  path: ^1.9.0

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and code quality
  flutter_lints: ^5.0.0

  # Code generation and testing tools
  build_runner: ^2.4.13
  json_annotation: ^4.9.0

# Flutter configuration
flutter:
  # Enable Material Design
  uses-material-design: true

  # Generate platform-specific code
  generate: true

  # Assets configuration
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  # Custom fonts configuration
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
        - asset: assets/fonts/Metropolis-ExtraBold.otf
          weight: 800
