// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVxH_pntpANuGNtevQmzEtyD-vz9TITiA',
    appId: '1:276241359851:web:44b1a3142163944f42efae',
    messagingSenderId: '276241359851',
    projectId: 'foodex-78a88',
    authDomain: 'foodex-78a88.firebaseapp.com',
    storageBucket: 'foodex-78a88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZjQKJkdD6_eF2LtuDlsL8xZK3TLSfmTM',
    appId: '1:276241359851:android:8dfd84241973798542efae',
    messagingSenderId: '276241359851',
    projectId: 'foodex-78a88',
    storageBucket: 'foodex-78a88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFlDLGD8cvV0psnPEzl7h4hbK1hj6d8Ec',
    appId: '1:276241359851:ios:600c4733ba4e5f1842efae',
    messagingSenderId: '276241359851',
    projectId: 'foodex-78a88',
    storageBucket: 'foodex-78a88.firebasestorage.app',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFlDLGD8cvV0psnPEzl7h4hbK1hj6d8Ec',
    appId: '1:276241359851:ios:600c4733ba4e5f1842efae',
    messagingSenderId: '276241359851',
    projectId: 'foodex-78a88',
    storageBucket: 'foodex-78a88.firebasestorage.app',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVxH_pntpANuGNtevQmzEtyD-vz9TITiA',
    appId: '1:276241359851:web:8724771ea3a18aac42efae',
    messagingSenderId: '276241359851',
    projectId: 'foodex-78a88',
    authDomain: 'foodex-78a88.firebaseapp.com',
    storageBucket: 'foodex-78a88.firebasestorage.app',
  );
}
