name: Flutter CI

on:
  push:
  pull_request:

jobs:
  analyze-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Static analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Build web
        run: flutter build web --release
      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
